version: '3.9'

services:
  web:
    build: .
    # command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0
    command: uvicorn app.main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/facloud
    depends_on:
      - db
  db:
    container_name: fastapi_cloud
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data    
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=facloud
      - POSTGRES_HOST=0.0.0.0
volumes:
  postgres_data: